# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XPjaIiPEK2l72UUfEQx5Rru3IwH7gSKN
"""

a = input()
c = set(a)
d = dict()

for v in c:
  count = a.count(v)
  d.update({v:count})

m = max(d, key = d.get)
print(m)