# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XPjaIiPEK2l72UUfEQx5Rru3IwH7gSKN
"""

a=input()
b=input()
a1=a.split()
b1=b.split()
a2=set(a1)
b2=set(b1)
c=a2.intersection(b2)
count=len(c)
print (count)